Findergers1.0/Controllers/DesappController.cs
using Findergers1._0.Models;
using Findergers1._0.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Findergers1._0.Controllers
{
    public class DesappController : Controller
    {
        public IActionResult Index()
        {
            List<ListMissing> lst;
            using (DesappDBContext db = new DesappDBContext())
            {
                lst = (from d in db.Missings
                       select new ListMissing
                       {
                           Id_Missing = d.IdMissing,
                           Name_Missing = d.NameMissing,
                           Age_Missing = d.AgeMissing,
                           Description_Missing = d.DescriptionMissing,
                           Date_Missing = d.DateMissing,
                           Lastlocation_Missing = d.LastlocationMissing,

                       }).ToList();

            }
            return View(lst);
        }
        //CREAR 
        public ActionResult NewMissing()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewMissing(Missing model)
        {
            if (ModelState.IsValid)
            {
                using (DesappDBContext db = new DesappDBContext())
                {
                    var oDesa = new Missing();

                    oDesa.IdMissing = model.IdMissing;
                    oDesa.NameMissing = model.NameMissing;
                    oDesa.AgeMissing = model.AgeMissing;
                    oDesa.DescriptionMissing = model.DescriptionMissing;
                    oDesa.DateMissing = model.DateMissing;
                    oDesa.LastlocationMissing = model.LastlocationMissing;

                    db.Missings.Add(oDesa);
                    db.SaveChanges();

                }
                return Redirect("~/Desapp/Index");
            }
            return View(model);
        }
        //Editar

        public ActionResult Edit(int ID)
        {
            Missing model = new Missing();
            using (DesappDBContext db = new DesappDBContext())
            {
                var oMis = db.Missings.Find(ID);
                model.IdMissing = oMis.IdMissing;
                model.NameMissing = oMis.NameMissing;
                model.AgeMissing = oMis.AgeMissing;
                model.DescriptionMissing = oMis.DescriptionMissing;
                model.DateMissing = oMis.DateMissing;
                model.LastlocationMissing = oMis.LastlocationMissing;

            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Missing model)
        {
            try
            {


                if (ModelState.IsValid)
                {
                    using (DesappDBContext db = new DesappDBContext())
                    {
                        var oDesa = db.Missings.Find(model.IdMissing);

                        oDesa.IdMissing = model.IdMissing;
                        oDesa.NameMissing = model.NameMissing;
                        oDesa.AgeMissing = model.AgeMissing;
                        oDesa.DescriptionMissing = model.DescriptionMissing;
                        oDesa.DateMissing = model.DateMissing;
                        oDesa.LastlocationMissing = model.LastlocationMissing;
                        db.Entry(oDesa).State = EntityState.Modified;
                        db.SaveChanges();

                    }
                    return Redirect("~/Desapp/Index");
                }
                return View(model);
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        //ELIMINAR
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            using (DesappDBContext db = new DesappDBContext())
            {
                var oDesa = db.Missings.Find(Id);
                db.Missings.Remove(oDesa);
                db.SaveChanges();

            }
            return Redirect("~/Desapp/Index");
        }


    }
}

Findergers1.0/Views/Desapp/Edit.cshtml
@model Findergers1._0.Models.Missing
@{
    ViewBag.Title = "Edit";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Desapp", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d=>d.IdMissing)
            <div>
                @Html.LabelFor(d => d.NameMissing)
                @Html.TextBoxFor(d => d.NameMissing, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.NameMissing, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.AgeMissing)
                @Html.TextBoxFor(d => d.AgeMissing, "", new { @class = "form-control" })

            </div>
            <div>
                @Html.LabelFor(d => d.DescriptionMissing)
                @Html.TextBoxFor(d => d.DescriptionMissing, "", new { @class = "form-control" })

            </div>
            <div class="form-group">
                <label asp-for="DateMissing" class="control-label"></label>
                <input asp-for="DateMissing" class="form-control" />
                <span asp-validation-for="DateMissing" class="text-danger"></span>
            </div>
            <div>
                @Html.LabelFor(d => d.LastlocationMissing)
                @Html.TextBoxFor(d => d.LastlocationMissing, "", new { @class = "form-control" })

            </div>
           


            <div style="text-align:right;">
                <input value="Save" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>

}

Findergers1.0/Views/Desapp/Index.cshtml
@model List<Findergers1._0.Models.ViewModels.ListMissing>

@{
    ViewBag.Title = "Missings";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Age</th>
                <th>Description</th>
                <th>Date</th>
                <th>Last location</th>
                
                <th> </th>
            </tr>
            @foreach (var oElemento in Model)
            {
                <tr>
                    <td>@oElemento.Id_Missing</td>
                    <td>@oElemento.Name_Missing</td>
                    <td>@oElemento.Age_Missing</td>
                    <td>@oElemento.Description_Missing</td>
                    <td>@oElemento.Date_Missing</td>
                    <td>@oElemento.Lastlocation_Missing</td>
                    
                    <td>
                        <a class="btn btn-default" href="~/Desapp/Edit/@oElemento.Id_Missing">Edit</a>
                        <a class="btn btn-danger" href="~/Desapp/Delete/@oElemento.Id_Missing">Delete</a>

                    </td>
                </tr>
            }

        </table>

    </div>
</div>

<tr>
    <td>
        <a href="/Desapp/NewMissing" class="btn btn-primary">Nuevo Registro</a>
    </td>
</tr>

Findergers1.0/Views/Desapp/NewMissing.cshtml
@model Findergers1._0.Models.Missing
@{
    ViewBag.Title = "New Registration";
}

<h2>@ViewBag.Title</h2>



@using (Html.BeginForm("NewMissing", "Desapp", FormMethod.Post))
{
   
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.NameMissing)
                @Html.TextBoxFor(d => d.NameMissing, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.NameMissing, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.AgeMissing)
                @Html.TextBoxFor(d => d.AgeMissing, "", new { @class = "form-control" })
            </div>

            <div>
                @Html.LabelFor(d => d.DescriptionMissing)
                @Html.TextBoxFor(d => d.DescriptionMissing, "", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="DateMissing" class="control-label"></label>
                <input asp-for="DateMissing" class="form-control" />
                <span asp-validation-for="DateMissing" class="text-danger"></span>
            </div>
            <div>
                @Html.LabelFor(d => d.LastlocationMissing)
                @Html.TextBoxFor(d => d.LastlocationMissing, "", new { @class = "form-control" })

            </div>

            <div style="text-align:right;">
                <input value="Save" class="btn btn-primary" type="submit" />
            </div>

        </div>



    </div>

}